# ==================================================
#
# LocalOps Localhost VirtualHost
# Static Configuration
#
# ==================================================

Define DOMAIN_NAME  "localhost" 
Define DOMAIN_DOC_ROOT "D:/LocalOpsExtender/public_html"
Define LOCAL_DOMAIN  "${DOMAIN_NAME}" 

# Centralized vHost Template
Include "${VHOST_TEMPLATE}/default-vhost.conf"