## Already assigned in core file: LoadModule autoindex_module modules/mod_autoindex.so

DirectoryIndex index.php index.html index.htm
AddHandler application/x-httpd-php .php

# ==============================================================================
# LocalOps php
# For auto update need to update the path
# Also need required dll name
# ==============================================================================
Define PHP_ROOT "C:/LocalOps/php"

# Define PHP6x "php-old-version"
# Define PHP7x "php-old-version"

Define PHP83 "php-8.3.31-Win32-vs16-x64"
Define PHP84 "php-8.4.23-Win32-vs17-x64"
Define PHP85 "php-8.5.8-Win32-vs17-x64"

# Define PHP9x "php-future-version"
# Define PHP10x "php-future-version"

Define ACTIVE_PHP "${PHP84}"

LoadModule php_module "${PHP_ROOT}/${ACTIVE_PHP}/php8apache2_4.dll"

# Keep folder name same to use `ACTIVE_PHP` work seamlessly

PHPIniDir "D:/LocalOpsExtender/apache24/php/${ACTIVE_PHP}"

# ==============================================================================
# LocalOps phpMyAdmin
# ==============================================================================

Alias /phpmyadmin "C:/LocalOps/phpMyAdmin"

<Directory "C:/LocalOps/phpMyAdmin">
    Options FollowSymLinks
    AllowOverride All
    Require all granted

    DirectoryIndex index.php
</Directory>

# ==============================================================================
# LocalOps vHost Data
# ==============================================================================

Define LOCAL_TLD ".dev.io"
Define VHOST_TEMPLATE "D:/LocalOpsExtender/apache24/conf/templates"

Include "D:/LocalOpsExtender/apache24/conf/sites-enabled/localops-localhost.conf" 
IncludeOptional "D:/LocalOpsExtender/apache24/conf/sites-enabled/*/*.conf" 