# LocalOps Default vHost Schema 

<Directory "${DOMAIN_DOC_ROOT}">
    Options +Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<VirtualHost *:80>

    ServerName ${LOCAL_DOMAIN}
    ServerAlias *.${LOCAL_DOMAIN}

    DocumentRoot "${DOMAIN_DOC_ROOT}"

    ErrorLog "logs/${LOCAL_DOMAIN}-error.log"
    CustomLog "logs/${LOCAL_DOMAIN}-access.log" combined

    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

</VirtualHost>

<VirtualHost *:443>

    ServerName ${LOCAL_DOMAIN}
    ServerAlias *.${LOCAL_DOMAIN}

    DocumentRoot "${DOMAIN_DOC_ROOT}"

    SSLEngine On
    SSLCertificateFile "D:/LocalOpsExtender/apache24/certs/wildcard.dev.io.pem"
    SSLCertificateKeyFile "D:/LocalOpsExtender/apache24/certs/wildcard.dev.io-key.pem"

    ErrorLog "logs/${LOCAL_DOMAIN}-error.log"
    CustomLog "logs/${LOCAL_DOMAIN}-access.log" combined

</VirtualHost>

# End of LocalOps universal vHost Schema
